### ISSUE TITLE
General Comments 

### ISSUE THREAD

**Issue by aruvimov** [int-eco-10/talk-01#4]
1) Abstract!!!
2) Conclusion!!!
3) Remove Acronyms page?
4) If we want to cut down the length, I would suggest cutting down Defense Mechanisms :P
But Attacks can definitely be cut too

**Comment by akehir** [comment]
1) your solution is perfect
2) WIP
3) done
4) WIP

**Comment by akehir** [comment]
4) done.

2) > needs some work.

**Comment by akehir** [comment]
2) done.
